Add script to enhance data from metadata api
serlo/metadata-exports pull request #111
Opened 2024-03-07 13:49 UTC by MoeHome

2024-03-07 15:45 UTC, MoeHome commented
I'm confused. When I start the script locally, it works as it should. When I start the tests locally all the licenses are missing in the generated file. And here online the licenses are there but one description is missing.

2024-03-11 16:33 UTC, MoeHome commented
> I'm confused. When I start the script locally, it works as it should. When I start the tests locally all the licenses are missing in the generated file. And here online the licenses are there but one description is missing.

The problems with the licenses was because I didn't compare the two files that should match. And the missing description is because of the test being a unit test and I extracted some logic from the function.

2024-03-11 18:18 UTC, kulla requested changes

2024-03-11 18:18 UTC, kulla commented on update_datenraum_nodes.py
> +    enhance_metadata(metadata_file, description_cache, ENHANCED_METADATA_PATH)
Can you put this into https://github.com/serlo/metadata-exports/blob/main/download_metadata.py -> so that it only runs one time?

2024-03-12 21:23 UTC, kulla approved these changes

2024-03-12 21:28 UTC, merged

2024-03-12 21:30 UTC, kulla commented
@MoeHome @AndreasHuber Thx :heart: This was the only bug which was left: https://github.com/serlo/metadata-exports/pull/111/commits/a7c7fe9351fdd33213c30802eb756e238b99a748